# Send this build to the travis.ci container-based infrastructure
# which typically has more capacity than the open-source Linux pool
sudo: false
# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
matrix:
  include:
    - python: "2.7"
      env: DJANGO_VERSION=1.10.8 REST_FRAMEWORK_VERSION=3.6.4
    - python: "2.7"
      env: DJANGO_VERSION=1.10.8 REST_FRAMEWORK_VERSION=3.7.7
    - python: "2.7"
      env: DJANGO_VERSION=1.11.10 REST_FRAMEWORK_VERSION=3.6.4
    - python: "2.7"
      env: DJANGO_VERSION=1.11.10 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.4"
      env: DJANGO_VERSION=1.10.8 REST_FRAMEWORK_VERSION=3.6.4
    - python: "3.4"
      env: DJANGO_VERSION=1.10.8 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.4"
      env: DJANGO_VERSION=1.11.10 REST_FRAMEWORK_VERSION=3.6.4
    - python: "3.4"
      env: DJANGO_VERSION=1.11.10 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.5"
      env: DJANGO_VERSION=1.10.8 REST_FRAMEWORK_VERSION=3.6.4
    - python: "3.5"
      env: DJANGO_VERSION=1.10.8 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.5"
      env: DJANGO_VERSION=1.11.10 REST_FRAMEWORK_VERSION=3.6.4
    - python: "3.5"
      env: DJANGO_VERSION=1.11.10 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.6"
      env: DJANGO_VERSION=1.10.8 REST_FRAMEWORK_VERSION=3.6.4
    - python: "3.6"
      env: DJANGO_VERSION=1.10.8 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.6"
      env: DJANGO_VERSION=1.11.10 REST_FRAMEWORK_VERSION=3.6.4
    - python: "3.6"
      env: DJANGO_VERSION=1.11.10 REST_FRAMEWORK_VERSION=3.7.7
before_install:
  - export DJANGO_SETTINGS_MODULE=tests.test_settings
  - export PIP_USE_MIRRORS=true
# Tell it the things it will need to install when it boots
install:
   # Install the dependencies the app itself has
   # which in this case I choose to keep in a requirements file
 - pip install -r requirements.txt
   # Install whatever version of Django that's listed above
   # Travis is currently working on
 - pip install -q Django==$DJANGO_VERSION
 - pip install djangorestframework==$REST_FRAMEWORK_VERSION
 - pip install coveralls
 - pip install flake8
# Tell Travis how to run the test script itself
script:
- flake8 textplusstuff/
- coverage run --source=textplusstuff runtests.py
after_success: coveralls
